### ISSUE TITLE
Unable to access the gui 

### ISSUE THREAD

**Issue by wadkarkundan** [yilozt/mutter-rounded-setting#2]
So I installed mutter-rounded along with mutter-rounded-=settings gui everything was successfully installed  but I can't seem to access the settings. How to do that please need help

**Comment by yilozt** [comment]
```
cd /path/to/mutter-rounded-setting
gjs ./dist/mutter_settings.js
```

Then you can see the gui if mutter-rounded is installed correctly.

**Comment by wadkarkundan** [comment]
> ```
> cd /path/to/mutter-rounded-setting
> gjs ./dist/mutter_settings.js
> ```
> 
> Then you can see the gui if mutter-rounded is installed correctly.

thanks a lot this worked.

**Comment by wadkarkundan** [comment]
Sorry but now the Blur doesn't seem to work no matter what value I set

**Comment by yilozt** [comment]
Need to pick a window to the list in the Blur settings.

**Comment by wadkarkundan** [comment]
> Need to pick a window to the list in the Blur settings.

Tried picking the window but unable to add it. I first click on the picker then select the window ex. file manager app but it doesnt load up still says new item.

*Update 
I found out why coz I just checked my Extensions and it has a extension Mutter-Rounded Pick a window incompatible with gnome 42. Any workaround I mean could I try disabling the Gnome version check validation and try?

**Comment by yilozt** [comment]
You can try disable the Gnome version check validation. It should works with gnome 42.

**Comment by yilozt** [comment]
Looks like I forget add gnome 42 into `metadata.json`

**Comment by wadkarkundan** [comment]
> Looks like I forget add gnome 42 into `metadata.json`

Prolly I'll just wait for it to support gnome 42. Can you update me once you've added that support. Thanks

**Comment by yilozt** [comment]
The extension to pick a window should works well if you have disable the version validating of extensions.

I have add 42 to metadata.json of this extensions. You can use `git pull` to update and run install.sh again. This extension should works when you relogin to gnome-session.


________________________________

**Comment by wadkarkundan** [comment]
> The extension to pick a window should works well if you have disable the version validating of extensions. I have add 42 to metadata.json of this extensions. You can use `git pull` to update and run install.sh again. This extension should works when you relogin to gnome-session.
> […](#)

Thanks now it works. I love the Blur effect what is your suggested settings values for the Blur. Also If you could add the reset value to default button would be great. Thanks for you help.
